from Setup.GuiSetup import UiSetup
from Setup.Auxiliares import setup_file_browser
from Setup.Auxiliares import resource_path
from Setup.Auxiliares import update_spin_boxes
from Setup.Auxiliares import setup_layers_tree
from Setup.Auxiliares import open_existing_project
from Setup.Auxiliares import update_file_browser_root
from Setup.Auxiliares import set_default_layout
from Setup.Auxiliares import show_context_menu
from Setup.Auxiliares import setup_second_tree
from Setup.Auxiliares import status_bar_message
from Setup.AjusteDock import AjusteDock